import { PERMISSIONS } from './permissions.js';

export const SYSTEM_ROLES = {
  ADMINISTRATOR: 'Administrator',
  MANAGEMENT: 'Management',
  SERVICE_CREW: 'Service Crew',
} as const;

export type SystemRoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.ACCOUNT_SUBMIT_EMPLOYEE_REQUIREMENTS,
  ),
  [SYSTEM_ROLES.MANAGEMENT]: [
    PERMISSIONS.ADMIN_VIEW_ALL_BRANCHES,
    PERMISSIONS.DASHBOARD_VIEW_PAYSLIP,
    PERMISSIONS.DASHBOARD_VIEW_PERFORMANCE_INDEX,
    PERMISSIONS.POS_VERIFICATION_VIEW,
    PERMISSIONS.POS_SESSION_VIEW,
    PERMISSIONS.ACCOUNT_SUBMIT_CASH_REQUEST,
    PERMISSIONS.ACCOUNT_SUBMIT_PRIVATE_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_SUBMIT_PUBLIC_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_AUTH_REQUESTS,
    PERMISSIONS.ACCOUNT_VIEW_CASH_REQUESTS,
    PERMISSIONS.ACCOUNT_VIEW_NOTIFICATIONS,
    PERMISSIONS.EMPLOYEE_EDIT_OWN_PROFILE,
    PERMISSIONS.EMPLOYEE_VIEW_ALL_PROFILES,
    PERMISSIONS.EMPLOYEE_VIEW_OWN_PROFILE,
    PERMISSIONS.SHIFT_VIEW_ALL,
    PERMISSIONS.AUTH_REQUEST_VIEW_ALL,
    PERMISSIONS.CASH_REQUEST_VIEW_ALL,
    PERMISSIONS.EMPLOYEE_VERIFICATION_VIEW,
    PERMISSIONS.STORE_AUDIT_PROCESS,
    PERMISSIONS.STORE_AUDIT_VIEW,
    PERMISSIONS.CASE_REPORT_CLOSE,
    PERMISSIONS.CASE_REPORT_CREATE,
    PERMISSIONS.CASE_REPORT_VIEW,
    PERMISSIONS.VIOLATION_NOTICE_VIEW,
    PERMISSIONS.PEER_EVALUATION_VIEW,
  ],
  [SYSTEM_ROLES.SERVICE_CREW]: [
    PERMISSIONS.DASHBOARD_VIEW_PAYSLIP,
    PERMISSIONS.DASHBOARD_VIEW_PERFORMANCE_INDEX,
    PERMISSIONS.POS_VERIFICATION_VIEW,
    PERMISSIONS.POS_VERIFICATION_CONFIRM_REJECT,
    PERMISSIONS.POS_VERIFICATION_UPLOAD_IMAGE,
    PERMISSIONS.POS_SESSION_VIEW,
    PERMISSIONS.ACCOUNT_VIEW_SCHEDULE,
    PERMISSIONS.ACCOUNT_VIEW_AUTH_REQUESTS,
    PERMISSIONS.ACCOUNT_SUBMIT_PUBLIC_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_CASH_REQUESTS,
    PERMISSIONS.ACCOUNT_SUBMIT_CASH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_NOTIFICATIONS,
    PERMISSIONS.ACCOUNT_VIEW_AUDIT_RESULTS,
    PERMISSIONS.EMPLOYEE_VIEW_OWN_PROFILE,
    PERMISSIONS.EMPLOYEE_EDIT_OWN_PROFILE,
    PERMISSIONS.VIOLATION_NOTICE_VIEW,
    PERMISSIONS.VIOLATION_NOTICE_CREATE,
  ],
};

export const DEFAULT_ROLE_COLORS: Record<string, string> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: '#e74c3c',
  [SYSTEM_ROLES.MANAGEMENT]: '#3498db',
  [SYSTEM_ROLES.SERVICE_CREW]: '#2ecc71',
};

export const DEFAULT_ROLE_PRIORITIES: Record<string, number> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: 100,
  [SYSTEM_ROLES.MANAGEMENT]: 50,
  [SYSTEM_ROLES.SERVICE_CREW]: 10,
};
