import { PERMISSIONS } from './permissions.js';

export const SYSTEM_ROLES = {
  ADMINISTRATOR: 'Administrator',
  MANAGEMENT: 'Management',
  SERVICE_CREW: 'Service Crew',
} as const;

export type SystemRoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.ACCOUNT_MANAGE_EMPLOYEE_REQUIREMENTS,
  ),
  [SYSTEM_ROLES.MANAGEMENT]: [
    PERMISSIONS.ADMIN_VIEW_ALL_BRANCHES,
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.ACCOUNT_MANAGE_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_SUBMIT_PRIVATE_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_MANAGE_CASH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_AUDIT_RESULTS,
    PERMISSIONS.AUTH_REQUEST_VIEW_PAGE,
    PERMISSIONS.AUTH_REQUEST_VIEW_PRIVATE,
    PERMISSIONS.AUTH_REQUEST_VIEW_PUBLIC,
    PERMISSIONS.AUTH_REQUEST_MANAGE_PRIVATE,
    PERMISSIONS.AUTH_REQUEST_MANAGE_PUBLIC,
    PERMISSIONS.EMPLOYEE_VERIFICATION_VIEW_PAGE,
    PERMISSIONS.EMPLOYEE_VERIFICATION_MANAGE_REGISTRATION,
    PERMISSIONS.EMPLOYEE_VERIFICATION_MANAGE_PERSONAL,
    PERMISSIONS.EMPLOYEE_VERIFICATION_MANAGE_REQUIREMENTS,
    PERMISSIONS.EMPLOYEE_VERIFICATION_MANAGE_BANK,
    PERMISSIONS.CASE_REPORT_VIEW,
    PERMISSIONS.CASE_REPORT_MANAGE,
    PERMISSIONS.STORE_AUDIT_VIEW,
    PERMISSIONS.STORE_AUDIT_MANAGE,
    PERMISSIONS.EMPLOYEE_PROFILES_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.VIOLATION_NOTICE_VIEW,
    PERMISSIONS.VIOLATION_NOTICE_MANAGE,
    PERMISSIONS.WORKPLACE_RELATIONS_VIEW,
    PERMISSIONS.CASH_REQUESTS_VIEW,
    PERMISSIONS.CASH_REQUESTS_MANAGE,
  ],
  [SYSTEM_ROLES.SERVICE_CREW]: [
    PERMISSIONS.POS_VIEW,
    PERMISSIONS.POS_MANAGE_VERIFICATIONS,
    PERMISSIONS.ACCOUNT_VIEW_SCHEDULE,
    PERMISSIONS.ACCOUNT_MANAGE_SCHEDULE,
    PERMISSIONS.ACCOUNT_MANAGE_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_MANAGE_CASH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_AUDIT_RESULTS,
    PERMISSIONS.ACCOUNT_MANAGE_EMPLOYEE_REQUIREMENTS,
    PERMISSIONS.VIOLATION_NOTICE_VIEW,
    PERMISSIONS.WORKPLACE_RELATIONS_VIEW,
  ],
};

export const DEFAULT_ROLE_COLORS: Record<string, string> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: '#e74c3c',
  [SYSTEM_ROLES.MANAGEMENT]: '#3498db',
  [SYSTEM_ROLES.SERVICE_CREW]: '#2ecc71',
};

export const DEFAULT_ROLE_PRIORITIES: Record<string, number> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: 100,
  [SYSTEM_ROLES.MANAGEMENT]: 50,
  [SYSTEM_ROLES.SERVICE_CREW]: 10,
};
