import { PERMISSIONS } from './permissions.js';

export const SYSTEM_ROLES = {
  ADMINISTRATOR: 'Administrator',
  MANAGEMENT: 'Management',
  SERVICE_CREW: 'Service Crew',
} as const;

export type SystemRoleName = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: Object.values(PERMISSIONS),
  [SYSTEM_ROLES.MANAGEMENT]: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.ADMIN_MANAGE_ROLES && p !== PERMISSIONS.ADMIN_MANAGE_USERS,
  ),
  [SYSTEM_ROLES.SERVICE_CREW]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ACCOUNT_VIEW_SCHEDULE,
    PERMISSIONS.ACCOUNT_VIEW_AUTH_REQUESTS,
    PERMISSIONS.ACCOUNT_SUBMIT_PRIVATE_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_SUBMIT_PUBLIC_AUTH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_CASH_REQUESTS,
    PERMISSIONS.ACCOUNT_SUBMIT_CASH_REQUEST,
    PERMISSIONS.ACCOUNT_VIEW_NOTIFICATIONS,
    PERMISSIONS.EMPLOYEE_VIEW_OWN_PROFILE,
    PERMISSIONS.EMPLOYEE_EDIT_OWN_PROFILE,
  ],
};

export const DEFAULT_ROLE_COLORS: Record<string, string> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: '#e74c3c',
  [SYSTEM_ROLES.MANAGEMENT]: '#3498db',
  [SYSTEM_ROLES.SERVICE_CREW]: '#2ecc71',
};

export const DEFAULT_ROLE_PRIORITIES: Record<string, number> = {
  [SYSTEM_ROLES.ADMINISTRATOR]: 100,
  [SYSTEM_ROLES.MANAGEMENT]: 50,
  [SYSTEM_ROLES.SERVICE_CREW]: 10,
};
